# fly.toml app configuration file generated for finaleproject on 2023-09-14T18:32:51+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "finaleproject"
primary_region = "waw"

[build]
  image = "berodev/finaleproject:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySettings__CloudName="doatgkyno"
  CloudinarySettings__ApiKey="566786123133895"


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
